apiVerison: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-express-ingress
  namespace: local-path-storage
spec:
  rules:
    - host: mongo-express.local
      http:
        paths:
          services:
            - name: mongo-express-service
              port:
                number: 8081