apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  label: 
   name: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
       path: "/mnt/data"
 
