<<<<<<< HEAD:react-express-mysql/compose.yaml
=======
version: "3.8"
>>>>>>> 8f216cbc6a4208b70433402eddba4015101d36fc:react-express-mysql/compose.yml
services:
  backend:
    build:
      args:
<<<<<<< HEAD:react-express-mysql/compose.yaml
      - NODE_ENV=development
=======
       - NODE_ENV=development 
>>>>>>> 8f216cbc6a4208b70433402eddba4015101d36fc:react-express-mysql/compose.yml
      context: backend
      target: development
    command: npm run start-watch
    environment:
<<<<<<< HEAD:react-express-mysql/compose.yaml
      - DATABASE_DB=example
      - DATABASE_USER=root
      - DATABASE_PASSWORD=/run/secrets/db-password
      - DATABASE_HOST=db
      - NODE_ENV=development
    ports:
      - 80:80
      - 9229:9229
      - 9230:9230
    secrets:
      - db-password
=======
      - NODE_ENV=development
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_DATABASE=backeddb
      - MYSQL_PASSWORD=/run/secrets/db_password
    ports:
      - "80:80"
      - "9229:9229"
      - "9230:9230"
    secrets:
      - db_password
>>>>>>> 8f216cbc6a4208b70433402eddba4015101d36fc:react-express-mysql/compose.yml
    volumes:
      - ./backend/src:/code/src:ro
      - ./backend/package.json:/code/package.json
      - ./backend/package-lock.json:/code/package-lock.json
      - back-notused:/opt/app/node_modules
    networks:
      - public
      - private
    depends_on:
      - db
<<<<<<< HEAD:react-express-mysql/compose.yaml
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - private
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
=======
  
  db:
    image: mariadb:10.5 
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=/run/secrets/db_password
      - MYSQL_DATABASE=backeddb
    secrets:
      - db_password
    volumes:
      - db-data:/var/lib/mysql  
    networks:
      - private
    
>>>>>>> 8f216cbc6a4208b70433402eddba4015101d36fc:react-express-mysql/compose.yml
  frontend:
    build:
      context: frontend
      target: development
    ports:
<<<<<<< HEAD:react-express-mysql/compose.yaml
      - 3000:3000
=======
      - "3030:3030"
>>>>>>> 8f216cbc6a4208b70433402eddba4015101d36fc:react-express-mysql/compose.yml
    volumes:
      - ./frontend/src:/code/src
      - /code/node_modules
    networks:
      - public
    depends_on:
      - backend
networks:
  public:
  private:
<<<<<<< HEAD:react-express-mysql/compose.yaml
volumes:
  back-notused:
  db-data:
secrets:
  db-password:
    file: db/password.txt
=======

volumes:
  back-notused:
  db-data:

secrets:
  db_password:    
    file: db/db_password.txt
>>>>>>> 8f216cbc6a4208b70433402eddba4015101d36fc:react-express-mysql/compose.yml
